### ISSUE TITLE
love it and add k780 info

### ISSUE THREAD

**Issue by daiday** [dheygere/k380-fn-lock-for-windows#3]
```
const unsigned char k780_seq_fkeys_on[] = {0x10, 0x02, 0x0c, 0x1c, 0x00, 0x00, 0x00};
const unsigned char k780_seq_fkeys_off[] = {0x10, 0x02, 0x0c, 0x1c, 0x01, 0x00, 0x00};
const int k780_pid = 0xc52b;
```
I use both k780 and k380.

**Comment by dheygere** [comment]
Hi @daiday, thanks for the contribution. I encourage you to fork this repo in order to add support for the k780.

**Comment by dheygere** [comment]
I created this fork for the k780 => https://github.com/dheygere/k780-fn-lock-for-windows/releases/
